### ISSUE TITLE
bookmarks: documentation of level

### ISSUE THREAD

**Issue by koppor** [ho-tex/oberdiek#18]
On page 6 of the documentation of the bookmarks package, it reads

> (done by package hyperref, see option bookmarkdepth).

`bookmarkdepth` is not documented in recent hyperref. Which option is meant?

**Comment by davidcarlisle** [comment]
I would guess it's bookmarksdepth  (with an s) that was intended

David

**Comment by koppor** [comment]
`bookmarksopenlevel` maybe? - I could not find the string `bookmarksdepth` in the manual.

Doesn't matter 😇 , the issue I had was with [tocbasic](https://www.ctan.org/pkg/tocbasic). I had the wrong `level` parameters there. The solution was, just to omit `level`.
