### ISSUE TITLE
font.fonts problem in hologo.sty

### ISSUE THREAD

**Issue by dohyunkim** [ho-tex/oberdiek#2]
After today's update of oberdiek bundle in TeX Live pretest, the following example compiled with lualatex,
```latex
\documentclass{article}
\usepackage{fontspec, hologo}
\begin{document}
\hologo{XeTeX}
\end{document}
```
fails with an error message
```
error: ...xmf-dist/tex/luatex/luaotfload/fontloader-2016-05-04.lua:16483: attempt to index field 'spacing' (a nil value)
```
The difference from yesterday's code can be found at [this site](http://tug.org/svn/texlive/trunk/Master/texmf-dist/tex/generic/oberdiek/hologo.sty?r1=41047&r2=41046&pathrev=41047).

**Comment by davidcarlisle** [comment]
On 12 May 2016 at 13:22, Dohyun Kim <notifications@github.com> wrote:

> After today's update of oberdiek bundle in TeX Live pretest, the following
> example compiled with lualatex,
>
> \documentclass{article}\usepackage{fontspec, hologo}\begin{document}\hologo{XeTeX}\end{document}
>
> fails with an error message
>
> error: ...xmf-dist/tex/luatex/luaotfload/fontloader-2016-05-04.lua:16483: attempt to index field 'spacing' (a nil value)
>
> The difference from yesterday's code can be found at this site
> <http://tug.org/svn/texlive/trunk/Master/texmf-dist/tex/generic/oberdiek/hologo.sty?r1=41047&r2=41046&pathrev=41047>
> .
>


Ah OK, thanks  will fix.

The previous checkin

http://tug.org/svn/texlive/trunk/Master/texmf-dist/tex/generic/oberdiek/hologo.sty?r1=30467&r2=30466&pathrev=30467

was a patch in texlive not mirrored in the documented sources or ctan so it
got lost as I took ctan  as the base for my  luatex 0.95 update
I'll add the change back to the documented source and rebuild

David
