### ISSUE TITLE
ifpdf downloaded from CTAN cannot generate sty

### ISSUE THREAD

**Issue by andrersimoes** [ho-tex/oberdiek#22]
Hi Mr. Oberdiek.

I'm having a strange problem with ifpdf.

I cannot generate a single sty file when i run latex on ifpdf.dtx. However, the compilation ends ok, releasing no error messages.

I've also tried the same with a different package (hologo), which, by the contrary, it ended up generating hologo.sty.

Is there any extra step for this specific case ?

I'm using Slackware 14.2 and TeX, Version 3.141592 (Web2C 7.5.4)

My input and output files goes inside this compressed package:
[ifpdf.aux.zip](https://github.com/ho-tex/oberdiek/files/840058/ifpdf.aux.zip)

Thanks in advance,
André Simões.

**Comment by davidcarlisle** [comment]
On 14 March 2017 at 01:57, andrersimoes <notifications@github.com> wrote:

> Hi Mr. Oberdiek.
>
> I'm having a strange problem with ifpdf.
>
> I cannot generate a single sty file when i run latex on ifpdf.dtx.
> However, the compilation ends ok, releasing no error messages.
>
> I've also tried the same with a different package (hologo), which, by the
> contrary, it ended up generating hologo.sty.
>
> Is there any extra step for this specific case ?
>
> I'm using Slackware 14.2 and TeX, Version 3.141592 (Web2C 7.5.4)
>
> My input and output files goes inside this compressed package:
> ifpdf.aux.zip
> <https://github.com/ho-tex/oberdiek/files/840058/ifpdf.aux.zip>
>
> Thanks in advance,
> André Simões.
>
>
ifpdf should be in any tex distribution (or available in its package
manager if you started wit ha really minimal distribution) so it is _very_
rare for anyone to need to install from ctan,  an ifpdf.ins is generated
locally but not in the distribution, sorry about that. Save this as
ifpdf.ins

\input docstrip
\keepsilent
\preamble
\endpreamble

\askforoverwritefalse

\generate{\file{ifpdf.sty}{\from{ifpdf.dtx}{package}}}

\endbatchfile

%%%%%%%%

and then running tex on ifpdf.ins will generate the .sty.

I'll arrange that either that gets on to ctan or (probably better)
re-enable it extraction from the dtx file, which I think got broken while
arranging things for the new luatex

Thanks for the report

David

**Comment by davidcarlisle** [comment]
Hopefully 
https://github.com/ho-tex/oberdiek/blob/master/ifpdf.dtx

works as you expect, processing with plain tex should extract the `.sty` file.

**Comment by andrersimoes** [comment]
Hi Mr. David.

I'm at my work now. And here we use Debian.

If i tex 
https://github.com/ho-tex/oberdiek/blob/master/ifpdf.dtx
I receive this message

# This is TeX, Version 3.14159265 (TeX Live 2015/dev/Debian) (preloaded format=tex)
# (./ifpdf.dtx
# ! Undefined control sequence.
# l.9           \ProvidesFile
#                           {ifpdf.dtx}

I've tried with "latex" command and it works.  But i receive no sty, too.

The good part is that your last "ins" file works pretty well !!!

I'll try the same from my computer at night, and I'll come back here to tell the results.

Thanks again.
André.

**Comment by davidcarlisle** [comment]
can you check your browser cache that you are seeing/downloading the
changed file, it should start like

$ head ifpdf.dtx
% \iffalse
%% Source File: ifpdf.dtx
%% Copyright 2016 Heiko Oberdiek and LaTeX3 project
%%
%% This file may be distributed under the terms of the LPPL.
%% See README for details.
%
%<*ignore>
\ifx\ProvidesFile\undefined\let\install y\fi
\ifx\install y\else



with the <*ignore><*install>  blocks being new and acting as the installer
if used with tex (or pdftex)
what you show is what would have happened before I changed it.

David

**Comment by andrersimoes** [comment]
Hi Mr. David.

I've copied all file contents directly from the last commit and the sty file generation is now working.

If you need some help to check a new deployment in CTAN's webpage just let me know.

Andre

**Comment by davidcarlisle** [comment]
thanks for letting me know, there is one further change I just made for
issue #23 that just came in today.

**Comment by davidcarlisle** [comment]
This is now on ctan, thanks for the comment.
