### ISSUE TITLE
[multidot]{grffile} failure with xelatex

### ISSUE THREAD

**Issue by kberry** [ho-tex/oberdiek#30]
with graphics in current tl, running xelatex on a doc containing
\usepackage[multidot]{grffile}
results in 

Package grffile Warning: \Gread@QTm of xetex.def not found on input line 259.                                                                   
Package grffile Warning: Unsupported \Gread@eps not patched on input line 303. 

and so `multidot` input files can't be used with `\includegraphics` (since the previous "internal" support for `multidot` files in `xetex.def` is also gone, per my other report).

it all works with tl17 as originally distributed, fails with current tl.

(originally discussed on tex-live list after leo liu report, 30jun17).

(aside: it's not helpful that github does not support uploading .tex files. argh.)
```latex
\documentclass{article}
\usepackage{graphicx}
\usepackage[multidot]{grffile}
\begin{document}
%\includegraphics{x.1.png}
\end{document}
```

**Comment by davidcarlisle** [comment]
graphics has always supported any filenames that the system can support, including multiple dots, just need some extra syntactic precautions (or keys specifying in the graphicx interface)  to guard the dots. That said, we should get grffile and graphics back in line. (although I don't have much time next few days, may need to be next week, unless someone else does it first:-)

**Comment by josephwright** [comment]
@davidcarlisle  I guess I'm 'someone else' :) If we update the kernel to deal with multiple dots then the fix here is easy enough.

**Comment by u-fischer** [comment]
I just tested both in miktex and texlive with pdflatex, lualatex and xelatex and it seems to work fine. Can the issue be closed?

**Comment by kberry** [comment]
with successful testing, sure. (I haven't retried since the original report.) Closing now. Thanks.
