### ISSUE TITLE
[Feature request] Exact back-reference with backref

### ISSUE THREAD

**Issue by Randl** [ho-tex/oberdiek#32]
As for now, back references allow to return to the section or to the page, however, I believe it would be more convenient to have an opportunity to jump to the same place I've left from, so that the reading flow wouldn't be broken. I've seen some old workaround at [TeX SE](https://tex.stackexchange.com/questions/54541/precise-back-reference-target-with-hyperref-and-backref), but something built in would be really nice.

**Comment by davidcarlisle** [comment]
Thanks for the suggestion and the tex.sx link. Seems a reasonable option (I suspect it would have to be an option, and off by default to avoid clashing with unknown number of citation packages)

Not sure when we can get round to feature requests but having them logged here in github is a good thing.

**Comment by pablgonz** [comment]
@davidcarlisle I vote to move this issue to hyperref repository :).

**Comment by u-fischer** [comment]
This doesn't belong in this repository as backref is in the hyperref repository. But beside this it wouldn't work: if you have e.g. three citations on a page pointing to the same bib entry, to which you want to jump back? Generally the best way to jump back after you triggered a link is to use the Alt+left arrow key on your keyboard.
