### ISSUE TITLE
[luacolor] color rubs off out of the boundaries of \textcolor

### ISSUE THREAD

**Issue by ralessi** [ho-tex/oberdiek#43]
I may have found a bug of either `luacolor` or `adjustbox`. Please consider the following:

````
\documentclass{article}

\usepackage{luacolor}
\usepackage{adjustbox}

\newcommand{\yop}[2]{\adjustbox{width=3cm}{#1}\adjustbox{width=3cm}{#2}}

\begin{document}

Try to make a dot after \verb|\textcolor{brown}{ho}|. The pdf output
seems ok, but even so, \verb|color=<somecolor>| as argument of
\verb|\adjustbox| doesn't work.

\textcolor{brown}{ho}

\yop{jah}{yah}

Then everything is brown, even the page number in the footer!

\end{document}
````

The brown color should not rub off `\textcolor{brown}{ho}.  With `xcolor` instead of `luacolor`, everything is ok.

**Comment by u-fischer** [comment]
The problem has not related to adjustbox it can be reduce to a problem between luacolor and graphics:

~~~~
\documentclass{article}

\usepackage{luacolor}
\usepackage{graphics}

\begin{document}
abc

\textcolor{red}{XXXX}

\resizebox{3cm}{!}{abc}

YYY
\end{document}
~~~~

**Comment by davidcarlisle** [comment]
![image](https://user-images.githubusercontent.com/1268738/48873057-ef1fd500-ede3-11e8-8677-78614a61961c.png)

**Comment by u-fischer** [comment]
The issue will be resolved with the next update.

**Comment by ralessi** [comment]
> The issue will be resolved with the next update. 
Many thanks!
