### ISSUE TITLE
\pdf@shellescape breaks with --no-shell-escape in LuaLaTeX

### ISSUE THREAD

**Issue by PhelypeOleinik** [ho-tex/oberdiek#45]
This issue was spotted in [this question](https://tex.stackexchange.com/q/447992/134574).

The following code breaks when compiled with `lualatex --no-shell-escape file.tex`:

```latex
\documentclass{article}
\usepackage{pdftexcmds}
\makeatletter
\count@=\pdf@shellescape
\makeatother
\begin{document}
\end{document}
```

When compiled with `--no-shell-escape` LuaTeX returns a `0` which, at the moment `\pdf@shellescape` is defined, has `\catcode` 9, so it disappears and `\pdf@shellescape` expands to `\numexpr \relax` and it breaks with `Missing number, treated as zero`.

I thought that maybe doing a local `\catcode` change while defining `\pdf@shellescape` would be one way to solve it. Or maybe moving the definition a few lines below, where the `\catcode` of `0` is back to 12.

In the StackExchange chat [Ulrike Fischer suggested](https://chat.stackexchange.com/transcript/message/46440713#46440713) to remove the `\directlua0` thing and the compatibility ti LuaTeX < 0.36 altogether (with a [very good argument](https://chat.stackexchange.com/transcript/message/46440861#46440861)).

**Comment by davidcarlisle** [comment]
Thanks I think that should be fixed now, and it's anyway safer to use a fixed catcode regime in these internal sprint functions.

**Comment by davidcarlisle** [comment]
the updated dtx has a changelog describing the fix, but not the fix, sorry, another update will be needed, re-opening.
