### ISSUE TITLE
thumbpdf obj compression warning useless? (from l3doc)

### ISSUE THREAD

**Issue by kberry** [ho-tex/oberdiek#46]
thumbpdf has a warning if \pdfobjcompresslevel>0:

Compressed PDF objects of PDF 1.5 are not supported

I suggest this warning is useless and should be made into a log-only message. Object compression and PDF 1.5 have been the default for years now, so everyone is going to see this. The lack of thumbnails in the output when one is actually expecting them is more likely to be noticed than one warning floating by on the terminal.

This comes up for me because hypdoc loads thumbpdf, and l3doc loads hypdoc. (I don't actually care about thumbnails, they are being "forced" on me.) I suppose hypdoc and/or l3doc could also avoid loading thumbpdf in this case, but who knows, maybe someday thumbpdf will be extended. Not likely, but ...

Meanwhile, there are two further warnings in this case:
Package thumbpdf Warning: Thumbnail data file `tb123mitt-widows-code.tpt' not found
Package hyperref Warning: Invalid value `000'

Clearly it's pointless to warn about no .tpt file in a case where the package does nothing. I suggest \endinput if \pdfobjcompresslevel>0.

I didn't look into the hyperref warning, but I surmise it is similar, and in any case is meaninglessly vague.

Thanks. Yours for cleaner runs,
Karl

**Comment by davidcarlisle** [comment]
I'll see what I can do, as far as I can see viewers that offer a thumbnail navigation view at all now make the small images on the fly anyway so I'm not sure thumbpdf really does anything useful now. Actually even the hyperdoc doc says on page 2 that loading thumbpdf isn't necessary these days...

So perhaps hypdoc should not load that unconditionally even if we change thumpdf to cut out the warnings.

**Comment by davidcarlisle** [comment]
oh if I run thumbpdf I get

`
Unescaped left brace in regex is illegal here in regex; marked by <-- HERE in m/\\UseRGB{ <-- HERE (\d+)}\\\s*\d+\s*R/ at /usr/local/texlive/2018/bin/x86_64-cygwin/thumbpdf line 1457.


`

Which was the perl change from last year (or year before?), It seems that this script hasn't been run recently, I'll try to get an update out.....

**Comment by davidcarlisle** [comment]
@kberry I just realised that thumpdf is a separate distribution so I can't fix it here (or anywhere) unless Heiko @oberdiek wants us to make another repo under ho-tex ?

**Comment by kberry** [comment]
"oberdiekgroup" already has permission to upload new versions of thumbpdf (in catalogue file thumbpdf.xml). i'll be greatly surprised if heiko objects. thanks for all your work.

**Comment by davidcarlisle** [comment]
@kberry  something like this? https://github.com/ho-tex/thumbpdf/commits/master

**Comment by oberdiek** [comment]
Hello,

On 2018-09-07 22:52, kberry wrote:
> "oberdiekgroup" already has permission to upload new versions of 
> thumbpdf (in catalogue file thumbpdf.xml). i'll be greatly surprised if 
> heiko objects. thanks for all your work.

No objections.

Many, many thanks.

Best regards
   Heiko

PS:
I am surprised that someone is using thumbpdf.
Adding thumbnails is a basic feature of PDF viewers
since years (decades). Yet, thumbpdf can do more,
adding different thumbnails to the PDF that are not
just minatures of the pages. But I do not have any
feedback about this feature since decades.

**Comment by davidcarlisle** [comment]
hyperdoc no longer forces load of thumbpdf, other issues being addressed in the new thumbpdf repo, so closing here.

**Comment by kberry** [comment]
Heiko - nothing in the current flurry was about actually using thumbpdf; it was merely included automatically with the hypdoc package (not any more), which was included automatically with l3doc.

thanks to both of you.
