### ISSUE TITLE
Strange (new) issue with cleveref and tmhtools

### ISSUE THREAD

**Issue by pamaury** [ho-tex/oberdiek#5]
Dear Maintainer,
I recently run into a very strange error when using cleveref together with thmtools and hyperref. This issue did not exist before and as far as I know, thmtools and cleveref have not been updated since then, so I guess something in

 hyperref changed. I attached a minimum example. The problem seems related to the "sibling=theorem" line. Removing this line, or either of hyperref or cleveref fixes the problem. The error is:
! LaTeX Error: No counter 'd' defined.
although there is absolutely no counter "d" involved. I noticed that removing the "sibling=theorem" line actually transforms the error into:
! LaTeX Error: No counter 'theorem' defined.

I also attached the full output of pdflatex with package versions and more latex debug output.

NOTE: for some reason the github interface won't let me attach the ZIP file, so here is the link to it: https://www.dropbox.com/s/hnem3u93kg2bsam/bug.zip?dl=0

**Comment by davidcarlisle** [comment]
I'll check your zip file thanks but the issue looks like

http://tex.stackexchange.com/questions/315462/texlive-2016-hyperref-cleverref-incompatibility

which was fixed in that case at the last release.

David

**Comment by davidcarlisle** [comment]
your test file works without error for me, you have

 hpdftex.def    2016/05/21 v6.83p Hyperref driver for pdfTeX


the current release (here on github and in ctan and texlive) is 2016/06/24 v6.83q 

David
