### ISSUE TITLE
\ltx@ifpackagewith for ltxcmds

### ISSUE THREAD

**Issue by Rimole** [ho-tex/oberdiek#55]
ltxcmds.sty defines `\ltx@ifpackageloaded` for `\@ifpackageloaded` and `\ltx@ifpackagelater` for `\@ifpackagelater`. For `\@ifpackagewith` I did not find a `\ltx@ifpackagewith`. Thus I would like to suggest this as enhancement.

**Comment by davidcarlisle** [comment]
the ones that are there are fairly simple tests but to do if packagewidth you would really have to implement the whole latex option passing mechanism.

Actually I'd be interested how you are using these commands, I haven't really seen much use for them. If the latex package loading has not been implemented none of these commands do anything very useful, if it has been implemented, then the commands would be available already under their original names and not needing the ltx@ prefix.
