### ISSUE TITLE
Wrong hyperlinks with titletoc

### ISSUE THREAD

**Issue by MLopez-Ibanez** [ho-tex/oberdiek#6]
hyperref somehow creates wrong hyperlinks for the section that appears immediately after a subsection in the TOC, when using the titletoc package.  Small reproducer below with pdftex. "Wrong hyperlinked section" should point to page 5, but it jumps to page 3 (with Okular in Ubuntu Linux). Information about programs, packages, versions is at the top of the file.

I can attach the PDF if desired.

[test.tex.txt](https://github.com/ho-tex/oberdiek/files/422268/test.tex.txt)

**Comment by pablgonz** [comment]
You can check this issue, apparently after all the updates is no longer valid.
(Puedes revisar esta issue, al parecer luego de todas las actualizaciones ya no es valida.)

**Comment by pablgonz** [comment]
@davidcarlisle I vote to close this issue, the hyperref package has its own repository and the bug was fixed.

**Comment by u-fischer** [comment]
Probably related to https://github.com/latex3/hyperref/issues/86, which has been resolved in titletoc. So I'm closing it.
