### ISSUE TITLE
pdfcrop fails with gs9.27

### ISSUE THREAD

**Issue by kberry** [ho-tex/oberdiek#63]
pdfcrop fails with gs9.27. (Not surprising since 9.27 made many incompatible changes.) I hope this is the right place to report it and that it can be fixed. Thanks ...

Example from Herb Schulz attached.
[CropTest.zip](https://github.com/ho-tex/oberdiek/files/3136127/CropTest.zip)

**Comment by u-fischer** [comment]
pdfcrop isn't in this repo. It would be better to try to contact Heiko Oberdiek. Or do you know someone good enough in perl and ghostscript to suggest a fix?

**Comment by kberry** [comment]
oberdiekgroup is listed as an uploader for pdfcrop, as part of the general "Heiko doesn't have time any more".

Anyway, I can try to write him and/or look at it myself. (More a PostScript problem than a Perl problem, presumably.) I just hoped I could pass it off elsewhere : ).

**Comment by aminophen** [comment]
My friend tells that gs returns wrong boundingbox by 'bbox' device: resolved upstream.
https://bugs.ghostscript.com/show_bug.cgi?id=700988

**Comment by kberry** [comment]
upstream fix confirmed by mactex people, closing.
