### ISSUE TITLE
\TextField and \ChoiceMenu don't begin at the start of the line whene there is no text before

### ISSUE THREAD

**Issue by CarLaTeX** [ho-tex/oberdiek#64]
Even if the \TextField and \ChoiceMenu are the first objects in a line with \noindent, they don't begin and the start of the line, there is a little gap.

See this post on TeX.SE: https://tex.stackexchange.com/questions/489283/why-dont-textfield-and-choicemenu-begin-at-the-start-of-the-line.

`\documentclass{article}
\usepackage{hyperref}
\usepackage{showframe}

\begin{document}
\begin{Form}[action=mailto:my_email@gmail.com?subject={The submitted form},encoding=html, method=post]
\noindent Why doesn't the following field begin at the start of the line?
\vspace{1ex}

\noindent\TextField[name=a,width=5cm,charsize=8pt, height=.5cm]{}
\vspace{4ex}

\noindent Adding \texttt{bordersep=0pt} doesn't help: 
\vspace{1ex}

\noindent\TextField[bordersep=0pt,name=b,width=5cm, height=.5cm]{}
\vspace{4ex}

\noindent The same with a choice menu:
\vspace{1ex}

\noindent\ChoiceMenu[combo, name=choice, width=5cm]{}{Choice 1, Choice 2}
\end{Form}
\end{document}`

**Comment by u-fischer** [comment]
this issue should be in the hyperref repo https://github.com/latex3/hyperref/issues.  I can't transfer directly as it is a different organization. Could you make a copy there and close here?

**Comment by CarLaTeX** [comment]
> this issue should be in the hyperref repo https://github.com/latex3/hyperref/issues. I can't transfer directly as it is a different organization. Could you make a copy there and close here?

[Done!](https://github.com/latex3/hyperref/issues/323#issue-2027749399)

**Comment by CarLaTeX** [comment]
Copied in the hyperref repo and closed here.
