### ISSUE TITLE
attachfile2 and LuaTeX 1.10.0

### ISSUE THREAD

**Issue by pablgonz** [ho-tex/oberdiek#69]
Hello, to run correctly using `lualatex` you need to use `\usepackage{luatex85}`, can you remove this dependency?
For example the following file:
```latex
\begin{filecontents*}{test.txt}
  A test file
\end{filecontents*}
\documentclass{article}
\usepackage{attachfile2}
%\usepackage{luatex85}
\begin{document}
Attach \textattachfile[color=0 0 1]{test.txt}{TEST}.
\end{document}
```
shows:
```
! Undefined control sequence.
\atfi@xform ->\immediate \pdfxform 
                                   \atfi@appearancebox \edef \atfi@appearanc...

l.8 ... \textattachfile[color=0 0 1]{test.txt}{TEST}
```
when using `LuaTeX`, Version 1.10.0 (TeX Live 2019) in fedora 30 (update).
Saludos

**Comment by u-fischer** [comment]
Thanks for the report. Yes the dependancy should be removed, but it is not done with a single fix - the driver uses a number of pdftex specific commands - so it will need some thinking.

**Comment by pablgonz** [comment]
Thanks for the prompt response, version 2.9 works perfectly.

**Comment by pablgonz** [comment]
Hi, after update my `TeXLive` 2019 distribution on linux
```
! LaTeX Error: File `atfi-luatex.def' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: def)
```
Thank you for your great work.

**Comment by u-fischer** [comment]
Yes, looks like an error in the upload. You can unpack the missing driver from attachfile2.dtx.

**Comment by pablgonz** [comment]
Thank you...
