### ISSUE TITLE
Broken links in the documentation of various packages

### ISSUE THREAD

**Issue by pablgonz** [ho-tex/oberdiek#75]
Hi, apparently the links to `ctan` in the `attachfile2` and `accsupp` documentation are broken, I've checked some more packages and apparently they are too.
A query related to this...all documentations have a link to `TeX Catalogue` but this seems to no longer exist (or I haven't been able to find them).
Greetings

**Comment by davidcarlisle** [comment]
Given the age of some of these documents broken links are not impossible, but I just checked attachfile2 and the links in section 3.1 to for example `CTAN:macros/latex/contrib/oberdiek/attachfile2.dtx`  work for me, linking to 

http://ctan.org/tex-archive/macros/latex/contrib/oberdiek/attachfile2.dtx

which in my case resolves to

http://anorien.csc.warwick.ac.uk/mirrors/CTAN/macros/latex/contrib/oberdiek/attachfile2.dtx



which works (although ctan would prefer to use https and not use tex-archive form these days)

The catalogue is no longer maintained at CTAN in the public format that Heiko was linking to, it is more or less

https://ctan.org/tex-archive/obsolete/help/Catalogue/entries

I should probably delete those sections, but was avoiding global edits on 90+ files that I didn't  originally write:-)

Could you confirm which links (other than catalogue) were broken?

It is possible that not all ctan mirrors redirect http to https so it would help if you could say which mirror was being used for http://ctan.org in your case.

**Comment by pablgonz** [comment]
And the link in References, page 42 
```
Scott Pakin: The attachfile package; 2005/02/20 v1.2; CTAN:macros/latex/
contrib/attachfile/
```
![imagen](https://user-images.githubusercontent.com/2289461/68705457-e08a7a80-056c-11ea-86ac-984ae3afd65a.png)
I think the problem is in the `\CTAN` macro that is used in the documentation, the references are not correct...and I think using `https` would be the right thing to do.

**Comment by davidcarlisle** [comment]
OK this is your mirror, for me the reference

http://ctan.org/tex-archive/macros/latex/contrib/attachfile/

works fine and resolves to 
https://ctan.org/tex-archive/macros/latex/contrib/attachfile/

but CTAN do ask not to use that form anyway and ask that people link to the

https://ctan.org/pkg/attachfile

form,

hmm applying a regex edit over a hundred files... what could go wrong.... 

I'll see  what I can do..

**Comment by davidcarlisle** [comment]
I removed the catalogue sections in commit 3fb9909

**Comment by pablgonz** [comment]
I don't know if it will be my `ctan` mirror, but, this is the address that is addressed correctly :
https://ctan.org/tex-archive/macros/latex/contrib/attachfile/attachfile.pdf
and becomes (in my case)
http://ctan.dcc.uchile.cl/macros/latex/contrib/attachfile/attachfile.pdf
I think `ctan` doesn't like that they overload their main server :)

**Comment by davidcarlisle** [comment]
I have changed the links to tds.zip files to use the form the ctan package pages use updated the .bib file references to use the https://ctan.org/pkg/zref form for each package, and changed the rest to use https not http, I would prefer to use the https://ctan.org/pkg/zref}, form in more places but as the text links to explicit tex-archive/.... paths that is tricky as a global edit.

can you build locally (the ./mkctan script should work if you have bash, not so much on windows) ?

I have not done a full build but I will do one soon (it takes an hour or so on this machine..) and could let you have a zip to try if you are interested?

**Comment by pablgonz** [comment]
```
! Undefined control sequence.
<argument> \CTANinstall 
             {install/macros/latex/contrib/oberdiek.tds.zip}
l.972 ...all/macros/latex/contrib/oberdiek.tds.zip}]
```

**Comment by davidcarlisle** [comment]
@pablgonz  sorry I just got that as well, I have only been using docstrip for 30 years, so I apparently haven't learnt that you need to edit the documented dtx file and if you just edit the .sty file (and don't check it in) it won't work for other people....
 
4a18cd38b2e330e4575cd1572afc965377f34828

**Comment by pablgonz** [comment]
jejejej...sometimes it happens, to all this, if you update everything, you will add the `Pull requests ` that you have pending?

**Comment by davidcarlisle** [comment]
@pablgonz  on the PR, as @u-fischer  comments in issue #37 there are some issues getting everything in place together, I defer to her judgement about what to do there and the timing of when to make changes. But in general for all latex not just this collection we do want it to be easier to generate PDF meeting the various accessibility standards.

On the test failure, I'll let this doc run finish, then look.

**Comment by davidcarlisle** [comment]
I broke something and then by coincidence it can;t link to my package

```
! Undefined control sequence.
l.3232 % \bibpackage
                  {ifthen}{David Carlisle}{2001/05/26}
```

@pablgonz  if you are doing a full ./mkctan build you will get the same ..

**Comment by pablgonz** [comment]
@davidcarlisle :I thought the error was on my side, `l3build ctan` fault in some test (and creation of zip),  now I'm running `./mkctan`...I'll wait until it's over.

**Comment by davidcarlisle** [comment]
@pablgonz  currently you can only use  `l3build check`   as until recently l3build could not cope with the requirements of this bundle with some files going to generic and some to latex etc, we (well Joseph) recently added a tds mapping feature to l3build so in principle we could probably do this with l3build now, but anyway I plan to split it in to smaller bundles (this evening was supposed to be a simple job of extracting the makerobust package before this issue made me edit every file:-)

so for now mkctan is the only way to build the package in the correct order, that was a script I reverse engineered from the original files as donloaded from ctan when we set up this repo.

**Comment by pablgonz** [comment]
@davidcarlisle It's a tremendous job you've done to keep this project up to date. I think there are still lines of `⟨*catalogue⟩` (catchfile for example) I have used :
```
grep -rn 'catalogue>' --include="*.*" oberdiek/
```
the process is over and the links are still broken... perhaps the correct line is:
```
\newcommand*{\CTAN}[1]{%
  \href{https://ctan.org/tex-archive/#1}{\nolinkurl{CTAN:#1}}%
}
```
At least it worked for me.

**Comment by davidcarlisle** [comment]
@pablgonz 

> `g/tex-archive/#`

oops yes, will fix...  I may try harder to find any links that are going to the package in general and  make them use /pkg rather than a tex-archive path,  more grepping needed...

**Comment by pablgonz** [comment]
@davidcarlisle Unfortunately that won't solve the whole problem, update my comment above.

**Comment by davidcarlisle** [comment]
@pablgonz  it's getting late so I may look tomorrow, and see if I can tune the regex, I may look and see if I can extract all the href and link check the full set.

**Comment by pablgonz** [comment]
Thank you very much for the time invested, it will be great in the future to see all this running using `l3build`, for now you might save some time by adding `--draftmode` on line 62 of `mkctan`.
```
real	30m45,625s
user	27m53,810s
sys	2m11,752s
```
I'll be watching for updates
Greetings

**Comment by pablgonz** [comment]
@davidcarlisle You work very fast, to all this perhaps the most important link is missing `https://github.com/ho-tex/oberdiek/issues`.

**Comment by davidcarlisle** [comment]
@pablgonz  "https://github.com/ho-tex/oberdiek/issues"
 should be in the title of every doc:

```

% \author{Heiko Oberdiek\thanks
% {Please report any issues at https://github.com/ho-tex/oberdiek/issues}\\
```
I must admit I thought it was in the header of the extracted .sty as well but (looking at zref.dtx) 

```
% Copyright (C) 2006-2012 by
%    Heiko Oberdiek <heiko.oberdiek at googlemail.com>
%    2016
%    https://github.com/ho-tex/oberdiek/issues
%
```

isn't used for the .sty a second preamble  is used for that which still has only Heiko's email


```
   Heiko Oberdiek <heiko.oberdiek at googlemail.com>
```

and doesn't mention the "Oberdiek Package Support Group" (as maintainers, I'll fix that later, thanks)

**Comment by pablgonz** [comment]
@davidcarlisle Very fast again, maybe it'll be nicer:
```
% \author{Heiko Oberdiek\thanks
% {Please report any issues at \url{https://github.com/ho-tex/oberdiek/issues}}\\
```

**Comment by davidcarlisle** [comment]
@pablgonz  oh, no link currently, hadn't noticed that:-)

**Comment by pablgonz** [comment]
@davidcarlisle Hello, some minor things (but related to the same thing)
1. zip warning: name not matched: oberdiek/hobsub*.sty
This is for line 101 of `mkctan`.
2. The file `oberdiek.pdf` refers to `hobsub` (which is now gone) and `https://github.com/ho-tex/oberdiek/` needs to be added.
3. Most of the documentation contains a section like this (for example):
```
4.5 Some details for the interested
Attached source. The PDF documentation on CTAN also includes the .dtx
source file. It can be extracted by AcrobatReader 6 or higher. Another option is
pdftk, e.g. unpack the file into the current directory:
pdftk hypdoc.pdf unpack_files output .
```
Which apparently is not correct, I have used ` pdfdetach -list hypdoc.pdf` (and in others) and no file appears.
Thanks again for everything.

**Comment by pablgonz** [comment]
@davidcarlisle Too fast....now if I think it's the last one :), I think `<ho-tex at tug.org>` shouldn't be in `oberdiek.pdf`

**Comment by davidcarlisle** [comment]
@pablgonz why not? That email address was set up specifically for this repository, not everyone has a github account.  Thanks for the help, but I plan to stop now and ship this:-)  (I do need to adjust the \thanks I just added so it doesn't mess up the bookmarks, then I'm done for this time.

**Comment by pablgonz** [comment]
@davidcarlisle 
Thank you very much for everything, I will close this, one thing before you upload everything to `ctan`, perhaps add
```
[2019/11/14]
- Update doc.
```
Until next time

**Comment by davidcarlisle** [comment]
@pablgonz  I _ought_ to update the dates and version numbers but for these global edits that is a bit of a pain and if I did ctan maintainers would have to update 90+ catalogue entries so I'm only dating teh changes that affect thecode (makerobust and holtxdoc this tine round)

**Comment by pablgonz** [comment]
@davidcarlisle I understand, I mistakenly thought I was following the `l3` package model :(.

**Comment by davidcarlisle** [comment]
@pablgonz  if I do specific doc edits, eg when extracting a package to its own repository then I'll update the version number/date  so most will get updated over time.

**Comment by pablgonz** [comment]
@davidcarlisle That would be great (and more comfortable for the people of `ctan`), hopefully some of the volunteers of this project will pass the configuration directly to `l3build`.

**Comment by pablgonz** [comment]
@davidcarlisle  One more (I didn't see it before, sorry) https://github.com/ho-tex/grffile/blob/master/grffile.dtx

**Comment by davidcarlisle** [comment]
@pablgonz  I have stressed ctan team enough this morning with oberdiek+hobsub+makerobust so I don't plan any release for a while, also grffile is not in this repo, this ticket is marked closed, can you open an issue on grffile and I'll get to it one day.   Also any further issues in this repo can you open a new ticket, thanks.
