### ISSUE TITLE
Update to the use of the `iftex` package

### ISSUE THREAD

**Issue by pablgonz** [ho-tex/oberdiek#76]
Just in order to keep this in mind for the future of this great project:
```
$ grep -rn '\RequirePackage{ifpdf}' --include="*.*" oberdiek/
oberdiek/pdfrender.dtx:577:\PdfRender@RequirePackage{ifpdf}[2010/01/28]
oberdiek/tabularht.dtx:623:\RequirePackage{ifpdf}
oberdiek/bmpsize.dtx:3085:\RequirePackage{ifpdf}
oberdiek/pdfcol.dtx:465:\PDFCOL@RequirePackage{ifpdf}[2007/09/09]
oberdiek/hypdestopt.dtx:334:\RequirePackage{ifpdf}[2007/09/09]
oberdiek/hypgotoe.dtx:314:\RequirePackage{ifpdf}[2007/09/09]
$ grep -rn '\RequirePackage{ifxetex}' --include="*.*" oberdiek/
oberdiek/testfiles/rotchiffre-test2.lvt:21:  \RequirePackage{ifxetex}[2010/09/12]
```

**Comment by davidcarlisle** [comment]
yes I know:-)  

I just plan to do that as updates occur pdftexcmds done, I should also do attachfile this time (as updating that for other reasons)

**Comment by pablgonz** [comment]
@davidcarlisle Great, if you think it's convenient you should close this issue (along with the issue (https://github.com/ho-tex/oberdiek/issues/6#issue-171620406) which is no longer valid).

**Comment by adoerflinger** [comment]
It seems that the current CTAN release results in compile errors due to the ifluatex.sty not found. Is there any quick workaround?

**Comment by u-fischer** [comment]
@adoerflinger the current version should work fine. Ensure that your system is up-to-date. If you are using miktex update in user *and* admin* mode and also update your package database.

**Comment by adoerflinger** [comment]
Thanks for the hint, I only updated in admin mode and not user mode. Works perfectly!

**Comment by davidcarlisle** [comment]
These should all be done in the release 

https://github.com/ho-tex/oberdiek/releases/tag/release-2019-12-29
