### ISSUE TITLE
Possible issue after MikTeX update?

### ISSUE THREAD

**Issue by tbslange** [ho-tex/oberdiek#78]
("C:\Program Files\MiKTeX 2.9\tex/latex/oberdiek\auxhook.sty"
Package: auxhook 2016/05/16 v1.4 Hooks for auxiliary files (HO)
)

! LaTeX Error: File `kvoptions.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
! Emergency stop.
<read *> 
         
l.260 \RequirePackage{kvoptions}[2009/07/21]

**Comment by pablgonz** [comment]
@tbslange See https://github.com/ho-tex/oberdiek/issues/77#issue-530718777

**Comment by davidcarlisle** [comment]
duplicate issue (and a miktex  issue not fixable here)
