### ISSUE TITLE
`\today` as argument in pdfdate leads to an error

### ISSUE THREAD

**Issue by LukasCBossert** [ho-tex/oberdiek#79]
Consider this MWE

```
\documentclass{article}
\usepackage{hyperxmp,hyperref}
\hypersetup{pdfdate={\today}}
\begin{document}
Hello World!
\end{document}
```
I get the message
> ! Argument of \hyxmp@pdf@to@xmp@date has an extra }.
><inserted text> 
>                \par 
>l.3 \hypersetup{pdfdate={\today}}

Is it a bug?

I already posted this at TeX.SE: https://tex.stackexchange.com/q/519410/98739

**Comment by u-fischer** [comment]
no it is not a hyperref bug. The key is provided by hyperxmp ( and must have a specific format described in the hyperxmp documentation).
