### ISSUE TITLE
Mark pdfcrypt as obsolete

### ISSUE THREAD

**Issue by pablgonz** [ho-tex/oberdiek#80]
Hi, according to the documentation:
```
Note: Since pdfTEX-1.10a (2003-01-16) encryption support was dropped! Thus
the package is now obsolete for recent pdfTEX versions.
```
I think it only confuses new users, when you have the bad habit of not reading the complete documentation and staying only with the description. This package really does nothing today.

**Comment by davidcarlisle** [comment]
I was planning to move this to the old-source repository and not distribute, but reading the code again apparently is still supported in vtex and while not commonly used, vtex is open source and still distributed so I think I'll keep the package as-is for now at least.
