### ISSUE TITLE
backref and multibib

### ISSUE THREAD

**Issue by zazarara** [ho-tex/oberdiek#81]
Hy,

It seems there is a little bug when using backref package and multibib.
The second bibliography created with \newcite has the line
\@writefile{brf}{\backcite{RAB_CMAME07}{{1}{(document)}{Doc-Start}}}
in the .aux file.
Unfortunately the .brf file is not created.
If I manually create the brf file for this second bibliography, the page backreferences work...

Find enclosed a minimal working example.
Thank you very much for your help.

``
\documentclass[a4paper,11pt,twoside]{book} 
\usepackage[utf8]{inputenc}    % pour les accents 
\usepackage[T1]{fontenc}
\usepackage[table]{xcolor}

\definecolor{bleu}{rgb}{.06, .39, 0.71}

\usepackage[pdftex,pdfborder={0 0 0},
      colorlinks=true,
      linkcolor=bleu,
      citecolor=bleu,
      urlcolor=bleu, %violet
      pagebackref=true,
      breaklinks=true,
      naturalnames=true,
      linktoc=all
      ]{hyperref}  
     

\usepackage[hyperpageref]{backref}% Page des citations
% \renewcommand*{\backreflastsep}{, }
\renewcommand*{\backreflastsep}{ et }
\renewcommand*{\backreftwosep}{, }
\renewcommand*{\backref}[1]{}
\renewcommand*{\backrefalt}[4]{%
   \ifcase #1 %
%     No citations.% use \relax if you do not want the "No citations"
%     message
     \relax
   \or
     Cité à la page~#2.%
%      Cité p. #4.%
   \else
     Cité aux pages~#2.%
%      Cité aux pages #4.%
   \fi%
 }
 

% multi bibliographies
\usepackage{multibib}
\newcites{mesrefs}{Bibliographie personnelle}

\begin{document}
 
Une première citation,
\citemesrefs{RAB_CMAME07}.\\
Et une deuxième citation
\cite{Lumley1967}.

%%%%%%%%%%%%%%%%%%%`
%% Bibliographie
%%%%%%%%%%%%%%%%%%  
\renewcommand{\bibname}{Bibliographie}

\bibliographystyle{apalike-fr}
\bibliography{bib1}
% \renewcommand{\bibname}{Références bibliographiques personnelles}
%

\bibliographystylemesrefs{alpha-fr}
\bibliographymesrefs{bib2}

%\backmatter  

\end{document}
``
bib1.bib
``
@incollection{Lumley1967,
  address = {Moscow},
  author = {Lumley, J. L.},
  booktitle = {Atmospheric turbulence and radio propagation},
  citeulike-article-id = {592403},
  editor = {Yaglom, A.M. and Tatarski, V.I.},
  keywords = {homogeneous},
  pages = {166--178},
  posted-at = {2006-04-20 16:40:24},
  priority = {2},
  publisher = {Nauka},
  title = {{The Structure of Inhomogeneous Turbulent Flows}},
  year = {1967}
}

bib2.bib
`@article{RAB_CMAME07,` 
author="I. Rami\`ere and Ph. Angot and M. Belliard",
title="A fictitious domain approach with spread interface for elliptic problems with general boundary conditions",
journal="Computer Methods in Applied Mechecanics and Engineering, vol. 196 (4-6), pp.766-781",
year="2007"}

**Comment by u-fischer** [comment]
This here is the wrong repository. backref is part of hyperref. So I'm closing here.
