### ISSUE TITLE
PDFCrop Mac OS CATALINA : !!! Ghostscript exited with error code 127 !!!

### ISSUE THREAD

**Issue by PhileasFoggy** [ho-tex/oberdiek#82]
Hello,

I'm trying to use pdfcrop with python 3.6 on a MacBook Pro OS 10.15.4. I have always an error when I compile my program during crop. 

My program lines are: 

import subprocess as sub
sub.call('pdfcrop toto.pdf toto.pdf', shell=True)

The error is :

!!! Ghostscript exited with error code 127 !!!

Ghostscript version : 9.50
Perl : 5.28

Could you help me please ?

Regards

**Comment by pablgonz** [comment]
@PhileasFoggy Hi, the perl script `pdfcrop` is not in this repository.

**Comment by PhileasFoggy** [comment]
I have finally find the solution.

The problem was with a file named 'gs', that pdfcrop was no able to find. Now it's ok. Copy and paste the 'gs' file in the good directory and it will work.

**Comment by pablgonz** [comment]
@PhileasFoggy  Very well, although the best solution is to adjust the PATH to find `gs` or use the `gscmd` option from `pdfcrop`. Anyway remember to close this issue.
Greetings.

**Comment by PhileasFoggy** [comment]
Thank you
