### ISSUE TITLE
`hyphsubst` does not work any more since a newer release.

### ISSUE THREAD

**Issue by alkatar21** [ho-tex/oberdiek#87]
I have updated my packages and since then the package no longer works. The previous package was installed at the beginning of 2019.
Below is a minimal example to reproduce:
```tex
\documentclass[12pt]{article}

\usepackage[utf8]{inputenc}
\usepackage[ngerman]{babel}
\usepackage[ngerman=ngerman-x-latest]{hyphsubst}

\begin{document}
\end{document}
```
The error message:
```
(...\MiKTeX\tex/generic/oberdiek\hyphsubst.sty
(...\MiKTeX\tex/generic/infwarerr\infwarerr.sty
)

! Package hyphsubst Error: Unknown pattern `ngerman-x-latest'.

See the hyphsubst package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.227 \ProcessOptions*
                      \relax
)
```
The Package: 
![grafik](https://user-images.githubusercontent.com/61387986/110974899-5a986280-835f-11eb-98e4-2534ada7f8c9.png)

**Comment by u-fischer** [comment]
a more modern way to load the patter is with babel:

~~~~
\documentclass[12pt]{article}
\usepackage[ngerman]{babel}
\babelprovide[hyphenrules=ngerman-x-latest]{ngerman}

\begin{document}
\end{document}

~~~~

Both methods works fine in texlive but fail in miktex. I wasn't able to activate the pattern there too. To me it looks like a miktex bug which should be reported there.

**Comment by alkatar21** [comment]
Ah, good to know. I think knowing how to make things more modern is something I lack in general.

I forgot to mention MiKTeX, but that's interesting. However, I admittedly don't know where to report and what to show there, since it's probably indirectly a bug in MiKTeX? Once I know that, I would then close the ticket here?

**Comment by u-fischer** [comment]
I opened an issue for miktex: https://github.com/MiKTeX/miktex-packaging/issues/233
