### ISSUE TITLE
\implies

### ISSUE THREAD

**Issue by thegaryking** [ho-tex/oberdiek#92]
\centernot doesn't work well with \implies for some reason.  the slash is over on the left, a quarter way over (at least as part of the beamer package)

**Comment by davidcarlisle** [comment]
Please always include a proper test file, it looks OK to me

![image](https://github.com/ho-tex/oberdiek/assets/1268738/91d98f39-548b-4da7-b01e-fa3cf0073485)


```
\documentclass{article}

\usepackage{centernot,amsmath}

\begin{document}

\[A \centernot\implies b\]
\[A \implies b\]

\end{document}
```

If there is a problem in beamer, you would need to make a suitable test and report there.

**Comment by u-fischer** [comment]
closing as not reproducible.
